### PR TITLE
Same behaviour as React keyboard events

### PR DESCRIPTION
**Pull request by ayrton**
This is an ongoing effort to have the exact same behaviour as [react keyboard events](https://facebook.github.io/react/docs/events.html#keyboard-events). 

Thanks to @princed for [pointing this out](https://github.com/ayrton/react-key-handler/issues/4#issuecomment-196232467).

### CODE REVIEW

**Comment by princed** [comment]
Just wondering, why not depend directly on https://github.com/facebook/react/blob/master/src/renderers/dom/client/utils/getEventKey.js? Looks like easiest way to keep consistency. And things like greenkeeper.io could be used to check compatibility with upcoming React versions.

**Comment by ayrton** [comment]
@princed is on my list of things to figure out, most likely I will do this tomorrow, together with what's left on the roadmap

**Comment by ayrton** [comment]
FYI @princed [this tweet](https://twitter.com/dan_abramov/status/718472855785193472) pretty much sums up why I'm not doing this.

**Comment by princed** [comment]
Of course it could be moved, there's greenkeeper.io for that in my opinion :)

**Comment by ayrton** [comment]
My major concern is that I'm not 100% sure how this would work when publishing this library, considering react is a peer dependency and react is stubbed out, so that the user can include whatever react version they prefer.

If you have any ideas, feel free to open a PR after I've merged in this one, happy to do what's best for the project.

**Pull request merged**
