### PR TITLE
Fix PropTypes deprecation warnings

### PR DESCRIPTION
**Pull request by HedgeHogBy**
PropTypes are becoming deprecated in React v16.0.0 and are hitting warnings in React v15.5.0, [migration guide](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html).

### CODE REVIEW

**Comment by emgeee** [comment]
Any chance of this getting merged soon?

**Comment by ayrton** [comment]
Thanks for your pull request, I'll try and have a look this weekend to merge this in and publish the package.

**Comment by zorahrel** [comment]
@ayrton we need this :D

**Comment by alberto2000** [comment]
Any merge happening soon?

**Comment by lcsrinaldi** [comment]
Any updates on this?

**Comment by lostboy** [comment]
This would be a great pr to merge, its the last package in my build not compatible with react 16 because of the proptypes dep. Crossing fingers.

**Comment by ayrton** [comment]
I would really love to merge this in but as mentioned in https://github.com/ayrton/react-key-handler/issues/104#issuecomment-308878052 I wonder what needs to be done about backwards compatibility and how other libraries handle this. As soon as I know this I'm happy to release a new version supporting the latest version of React.

**Comment by HedgeHogBy** [comment]
According to [migration guide](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html) I mentioned:

> The propTypes, contextTypes, and childContextTypes APIs will work exactly as before. The only change is that the built-in validators now live in a separate package.

I hope it could help somehow :)

**Comment by lostboy** [comment]
@ayrton from what i've seen other maintainers have upgraded their projects with no compatibility issues. Example from react-measure https://github.com/souporserious/react-measure/commit/7bd868217bf24e947290c1cca703d31d6947cb7c

Your existing npm versions will work as is and all future versions will use PropTypes which has the same API as @HedgeHogBy pointed out.

**Comment by ayrton** [comment]
Thanks, will look tonight to get this merged in and publish a new version

**Pull request merged**
